spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: qwerty
    url: jdbc:postgresql://localhost:5432/bankapp_db
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect